[build]
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [[redirects]]
  from = "/"
  to ="/sasa.html"
  force = true
  status = 200
  conditions = {Role = ["registered"]}

 



  

 